service: serverless-aws-nodejs
provider:
 name: aws #Define the cloud provider to use
 runtime: nodejs8.10 
 stage: dev
 region: eu-central-1
functions:
 app:
  handler: app.server
  events: #Define the events that trigger the lambda
   - http: #Define an HTTP endpoint that respond to the / route
      path: /
      method: ANY #Define the HTTP methods to be used (GET/POST)
      cors: true
   - http: #Define an HTTP endpoin that respond to any routes
      path: /{proxy+}
      method: ANY
      cors: true